aplications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "persona_app"

urlpatterns = [
    path(
        "",
        views.InicioView.as_view()
        ,name="inicio"
        ),
    path(
        "listar-todo-empleados/", 
        views.ListAllempleados.as_view(),
        name="empleados_all"
        ),
    path(
        "listar-by-area/<shortname>/",
        views.ListByAreaEmpleado.as_view(),
        name="lista_depa"
        ),
    path("buscar-empleado/", views.ListEmpleadosByKword.as_view()),
    path("listar-habilidades-empleado/", views.Prueba.as_view()),
    path(
        "ver-empleado/<pk>/", 
        views.EmpleadoDetailView.as_view(),
        name="empleado_detail"
        ),
    path(
        "add-empleado/",
         views.EmpleadoCreateView.as_view(),
         name= "empleado_add"
         ),
    path("success/",views.SuccessView.as_view(),name="correcto"),
    path("update-empleado/<pk>/", views.EmpleadoUpdateView.as_view(),name="modificar_empleado"),
    path("delete-empleado/<pk>/",views.EmpleadoDeleteView.as_view(),name="eliminar_empleado"),
    path(
        "admin_empleados/", 
        views.ListaAdminempleados.as_view(),
        name="admin_all"
        ),
    
]

empleado/urls.py
#from empleado.empleado.settings.local import STATIC_URL
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # incluimos las URL del App departamento
    re_path("", include("aplications.departamento.urls")),
    re_path("", include("aplications.persona.urls")),
    re_path("", include("aplications.home.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplications/persona/models.py
from django.db import models
from aplications.departamento.models import Departamento
from ckeditor.fields import RichTextField


class Habilidades(models.Model):
    habilidad = models.CharField("Habilidad", max_length=50)
    
    class Meta:
        verbose_name = "Habilidad"
        verbose_name_plural = "Habilidades Empleado"
        
    def __str__(self):
        return str(self.id) + " - " + self.habilidad  

# Create your models here.
class Empleado(models.Model):
## Modelo para Tabla Empleado ###

    JOB_CHOICES = (
         ("0", "CONTADOR"),
         ("1", "ADMINISTRADOR"),
         ("2", "ECONOMISTA"),
         ("3", "OTRO"),


    )
    #Contador
    #Administrador
    first_name = models.CharField("Nombres",max_length=60,unique = False)
    last_name = models.CharField("Apellidos",max_length=60,unique = False)
    full_name = models.CharField("Nombre Completo",max_length=120,unique = False, blank=True)
    job = models.CharField("Trabajo", max_length=50, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    habilidades = models.ManyToManyField(Habilidades)
    avatar = models.ImageField(upload_to="empleado", blank=True, null=True)
    ##hoja_vida = RichTextField()


    class Meta:
        verbose_name = "Empleado"
        verbose_name_plural = "Empleados"
        ordering = ["first_name"]
        unique_together =("first_name", "last_name")


    
    def __str__(self):
        return str(self.id) + " - " + self.first_name + " - "+ self.last_name + " - "+ str(self.departamento)

aplications/persona/views.py
from typing import List
from django.shortcuts import render
from django.views.generic import *
from django.views.generic import(TemplateView, UpdateView, DeleteView ) 


from django.urls import reverse_lazy
from .models import Empleado
# Create your views here.


class InicioView(TemplateView):
    #vista que carga la pagina de Inicio#
    template_name = "inicio.html"


class ListAllempleados(ListView):
    
    template_name = 'persona/list_all.html'
    paginate_by = 5
    ##ordering = ['id','last_name']
    context_object_name ="empleados"

    def get_queryset(self):
        print("********--------*******")
        palabra_clave = self.request.GET.get("kword","")
        lista = Empleado.objects.filter(
        first_name__icontains= palabra_clave
        )
        lista = Empleado.objects.order_by('id')
        print(lista)
        return lista

class ListByAreaEmpleado(ListView):
        ## Lista de empleados de un area ##
    template_name = 'persona/list_by_area.html'

    def get_queryset(self):
        area = self.kwargs['shortname']
        lista = Empleado.objects.filter(
        departamento__name = area
        )
        return lista

class ListEmpleadosByKword(ListView):

    ## lista empleados por palabra ##
    template_name = 'persona/by_kword.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        print('***************')
        palabra_clave = self.request.GET.get("kword","")

        lista = Empleado.objects.filter(
        first_name = palabra_clave
        )
        return lista

class ListaHabilidades(TemplateView):

    template_name = 'persona/habilidades.html'
    paginate_by = 4
    ordering = "first_name"
    model = Empleado
    
    
class Prueba(ListView):
    template_name = 'persona/habilidades.html'
    context_object_name = "habilidades"

    def get_queryset(self) :
        empleado = Empleado.objects.get(id=2)
        print(empleado.habilidades.all())
        return empleado.habilidades.all()


class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detail_empleado.html"

    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context["titulo"]= " Empleado del mes"
        return context


class SuccessView(TemplateView):
    template_name = "persona/success.html"

 
class EmpleadoCreateView(CreateView):
     model = Empleado
     template_name = "persona/add.html"
     fields =[
         "first_name",
         "last_name",
         "job",
         "departamento",
         "habilidades",
         "avatar",
         ]
     #fields = ("__all__")
     success_url = reverse_lazy('persona_app:correcto')

     def  form_valid(self,form):

         empleado =form.save()
         empleado.full_name = empleado.first_name + ' '+ empleado.last_name
         empleado.save()

         return super(EmpleadoCreateView,self).form_valid(form)



class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "persona/update.html"
    fields =[
         "first_name",
         "last_name",
         "job",
         "departamento",
         "habilidades",
         ]
    success_url = reverse_lazy('persona_app:admin_all')
    
    def post(self, request, *args, **kwargs):
       self.object = self.get_object()
       print("***********************************")
       print(request.POST)
       print(request.POST["last_name"])
       print("***********************************")




       return super().post(request, *args, **kwargs)     

    def  form_valid(self,form):

         print("++++++++++++++++++++++++++++++++++++")

         return super(EmpleadoUpdateView,self).form_valid(form)   


 
class EmpleadoDeleteView(DeleteView):
     model = Empleado
     template_name = "persona/delete.html"
     success_url = reverse_lazy('persona_app:admin_all')     



class ListaAdminempleados(ListView):
    template_name = 'persona/admin_empleado.html'
    paginate_by = 10
    ordering = "last_name"
    context_object_name ="empleados"

    def get_queryset(self):
        print("********--------*******")  
        palabra_clave = self.request.GET.get("kword","")
        lista = Empleado.objects.filter(
        first_name__icontains= palabra_clave
        )
        lista = Empleado.objects.order_by('id')
        print(lista)
        return lista

templates/persona/add.html
{% extends 'base.html' %}
{% block title %}
        Agregar Empleado
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}




<
<div class="grid-container ">
  <div class="grid-x " >
    <h1 class = "cell">Agregar Empleado </h1>
     <h1></h1>
    
     <div class="callout">
            
         <form class = "cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}

         <div class="medium-6 cell">
           <label>Nombre
               {{form.first_name}}
           </label>
         </div>

         <div class="medium-6 cell">
           <label>Apellido
             {{form.last_name}}
           </label>
         </div>

         <div class="medium-6 cell">
          <label>Trabajo
              {{form.job}}
          </label>
      </div>

         <div class="medium-6 cell">
             <label>Departamento
                 {{form.departamento}}
             </label>
         </div>

         <div class="medium-6 cell">
             <label>Habilidades
                 {{form.habilidades}}
             </label>
         </div> 
         
         <div class="medium-6 cell">
           <label>Foto
               {{form.avatar}}
           </label>
       </div>    
   
  



   <div class= "cell">  

    
     
     <button type="submit" class="success button">Agregar Empleado</button>   
     
     
   </div>
 </form>


{% endblock content %}

<form method="POST">{% csrf_token %}

  {{form.as_p}}
  <button type="submit">Agregar</button>

</form>

templates/persona/admin_empleado.html
{% extends 'base.html' %}


{% block title %}

Lista de Empleados
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
     <div class="grid-x">
       <h1 class = "cell">Lista de Empleados</h1>
               <form class= "cell grid-x grid-margin-x" method="GET">{% csrf_token %}
                <div class="cell large-7">
                   <input type="text" name="kword" id="kword" placeholder="Buscar Empleado">
                </div>
                <div class="cell large-4">
                    <button type="summit" class="success button">Buscar</button>
                </form>
              </div>
           <div class= "cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">EDITAR</th>
                    <th width="150">ELIMINAR</th>
                    
                  </tr>
                </thead>
                <tbody>
                  {% for e in empleados %}
                  <tr>
                    <td>{{e.id}}</td>
                    <td>{{e.first_name}}</td>
                    <td>{{e.last_name}}</td>
                    <td>{{e.departamento}}</td>
                    <td><a class="button success" href="{% url 'persona_app:modificar_empleado' e.id %} ">Editar</a></td>
                    <td><a class="button alert" href="{% url 'persona_app:eliminar_empleado' e.id %}">Eliminar</a></td>
                    
                    
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
           </div>

      <div class= "cell">  
        
        {% if is_paginated %}
          
        <nav aria-label="Pagination">
          <ul class="pagination">
            
            {% if page_obj.has_previous %}
            <li class="pagination-previous ">
               <a href="?page={{page_obj.previous_page_number}}"  >Atras</a>
              </li>
            {% endif %}

            {% for pagina in paginator.page_range %}

            {% ifequal pagina page_obj.number  %} 
            <li class="current"><span class="show-for-sr">You're on page</span> {{pagina}}</li>
            
            {% else %}
            <li><a href="?page={{pagina}}" >{{pagina}}</a></li>  
            
            {% endifequal %}
            {% endfor %}
              
            
            {% if page_obj.has_next %}
            <li class="pagination-next">
              <a href="?page={{page_obj.next_page_number}}"  >Siguiente</a>
              {% endif %}

          </ul>
        </nav>
        {% endif %}

      </div>
        
    </div>
  </div>
    


{% endblock content %}

templates/persona/by_kword.html
<h1>Buscar empleado por palabra cable</h1>
<form method="GET">{% csrf_token %}
    <input type="text" name="kword" id="kword" placeholder="Ingrese nombre aquí">
    <button type="submit">Buscar</button>

</form>

<h3>Lista resultados</h3>

<ul>

{% for e in empleados %}
    
<li>{{e}}</li>

{% endfor %}
    


</ul>

templates/persona/delete.html
{% extends 'base.html' %}
{% block title %}
        Eliminar Empleado
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
     <div class="grid-x">
       <h1 class = "cell">Eliminar Empleado </h1>
        <h1></h1>
       
        <div class="callout">
            <h5>Informacion de: {{empleado.first_name}} {{empleado.last_name}}</h5>
            
        <form  class="cell grid-x grid-margin-x"method="POST" >{% csrf_token %}
           
            <table>
                <thead>
                  <tr>
                    <th width="150">ID</th>
                    <th width="150">NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="300">DEPARTAMENTO</th>
                    <th width="150">ACCION</th>
                    
                  </tr>
                </thead>
                <tbody>
                  
                  <tr>
                    <td>{{empleado.id}}</td>
                    <td>{{empleado.first_name}}</td>
                    <td>{{empleado.last_name}}</td>
                    <td>{{empleado.departamento}}</td>
                    <td><button type="submit"class="alert button">Borrar</button>          
                  </tr> 
                </tbody>
              </table>

    </div>    
           
    <div>       
         
    </div> 

    </form>  

      <div class= "cell">  
        
       
        

{% endblock content %}

templates/persona/detail_empleado.html
{% extends 'base.html' %}

{% load static %}

{% block title %}

Empleado {{empleado.first_name}}
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
   <div>
    
   </div>
   <div class="grid-x align-center">
    <div class="cell large-12 card" style="width: 300px;">
      <div class="card-divider">
        {{empleado.get_job_display}}
      </div>
      {% if empleado.avatar %}
         <img src="{{empleado.avatar.url}}">
      {% else %}
         <img src="{% static 'img/01.jpg' %}">
      {% endif %}
      
      <div class="card-section">
        <td>{{ empleado.first_name }}</td>
        <td>{{ empleado.last_name }}</td>
        <p><td>{{empleado.departamento.shor_name}}</td></p>
        <p><span class="label">Habilidades: </span> </p>
        <ul class="vertical menu">  
          
          {% for h in empleado.habilidades.all %}
            <li>{{h.habilidad}}</li>
          {% endfor %}
            
        </ul>
        
      </div>
    </div>



    <div>

      <h1>Info de Empleado</h1>
        <div class="cell">
            <table>
              <thead>
                <tr>
                  
                  <th width="150">NOMBRE</th>
                  <th width="150">APELLIDO</th>
                  <th width="150">DEPARTAMENTO</th>
                  <th width="150">HABILIDADES</th>
                  
                </tr>
              </thead>

                <tbody>
                     
                    <tr>
                        
                        <td>{{ empleado.first_name }}</td>
                        <td>{{ empleado.last_name }}</td>
                        <td>{{empleado.departamento}}</td>
                        <td>{{empleado.habilidades}}</td>
                    </tr>
                    
                </tbody>
            </table>
        </div>
   </div>
</div>
</div>


{% endblock content %}

<h3>Todos los datos</h3>

<p>{{ empleado.first_name }}</p>
<p>{{ empleado.last_name }}</p>
<p>{{empleado.departamento}}</p>
<p>{{empleado.habilidades}}</p>

templates/persona/habilidades.html
<h1>Lista de todos los empleados</h1>

<ul>

{% for h in habilidades %}
    <li>
        {{h}}
    </li>
{% endfor %}
    
</ul>

templates/persona/list_all.html
{% extends 'base.html' %}


{% block title %}

Lista de Empleados
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
     <div class="grid-x">
       <h1 class = "cell">Lista de Empleados</h1>
               <form class= "cell grid-x grid-margin-x" method="GET">{% csrf_token %}
                <div class="cell large-7">
                   <input type="text" name="kword" id="kword" placeholder="Buscar Empleado">
                </div>
                <div class="cell large-4">
                    <button type="summit" class="success button">Buscar</button>
                </form>
              </div>
           <div class= "cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">ACCION</th>
                    
                  </tr>
                </thead>
                <tbody>
                  {% for e in empleados %}
                  <tr>
                    <td>{{e.id}}</td>
                    <td>{{e.first_name}}</td>
                    <td>{{e.last_name}}</td>
                    <td>{{e.departamento}}</td>
                    <td><a class="button warning" href=" {% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>

                    
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
           </div>

      <div class= "cell">  
        
        {% if is_paginated %}
          
        <nav aria-label="Pagination">
          <ul class="pagination">
            
            {% if page_obj.has_previous %}
            <li class="pagination-previous ">
               <a href="?page={{page_obj.previous_page_number}}"  >Atras</a>
              </li>
            {% endif %}

            {% for pagina in paginator.page_range %}

            {% ifequal pagina page_obj.number  %} 
            <li class="current"><span class="show-for-sr">You're on page</span> {{pagina}}</li>
            
            {% else %}
            <li><a href="?page={{pagina}}" >{{pagina}}</a></li>  
            
            {% endifequal %}
            {% endfor %}
              
            
            {% if page_obj.has_next %}
            <li class="pagination-next">
              <a href="?page={{page_obj.next_page_number}}"  >Siguiente</a>
              {% endif %}

          </ul>
        </nav>
        {% endif %}

      </div>
        
    </div>
  </div>
    


{% endblock content %}

templates/persona/list_by_area.html
{% extends 'base.html' %}


{% block title %}

Lista de Departamentos
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
   <div class="grid-x">
      <h1>Lista de departamento</h1>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="150">ID</th>
                    <th width="150">NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">ACCIÓN</th>
                  </tr>
                </thead>
                <tbody>
                  {% for e in object_list %}
                  <tr>
                    <td>{{e.id}}</td>
                    <td>{{e.first_name}}</td>
                    <td>{{e.last_name}}</td>
                    <td>{{e.departamento}}</td>
                    <td><a class="button warning" href=" {% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>  
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
        </div>
   </div>
</div>



{% endblock content %}

templates/persona/success.html
{% extends 'base.html' %}
{% block title %}
        Felicidades
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}


<div class="grid-container">
     <div class="grid-x grid-margin-x">
       
    <h3 class = "cell">Actualización Exitosa</h3>

    <a class="button success" href="{% url 'persona_app:empleados_all' %} ">Finalizar</a></td>

    
    </form>  

      <div class= "cell">  
        
       
        

{% endblock content %}





<h1>Felicidades se creo correctamente el empleado</h1>

templates/persona/update.html
{% extends 'base.html' %}


{% block title %}

Lista de Empleados
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
     <div class="grid-x grid-margin-x">
       <h1 class = "cell">Actualizar Empleado</h1>
       <form class= "cell grid-x grid-margin-x" method="POST">{% csrf_token %}

        {{form.as_p}}
        <button type="submit" class="success button">Actualizar</button>
    
    </form>  
   
      <div class= "cell">  
        
       
        

{% endblock content %}