aplications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

def DesdeApps(self):
         print("hola mundo")

app_name = "departamento_app"         

urlpatterns = [
    
    path("new-departamento/", views.NewDepartamentoView.as_view(), name= "prueba_add"),
    path("lista-departamento/", views.DepartamentoListView.as_view(), name= "lista_departamento"),
]

aplications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "persona_app"

urlpatterns = [
    path(
        "",
        views.InicioView.as_view()
        ,name="inicio"
        ),
    path(
        "listar-todo-empleados/", 
        views.ListAllempleados.as_view(),
        name="empleados_all"
        ),
    path(
        "listar-by-area/<shortname>/",
        views.ListByAreaEmpleado.as_view(),
        name="lista_depa"
        ),
    path("buscar-empleado/", views.ListEmpleadosByKword.as_view()),
    path("listar-habilidades-empleado/", views.Prueba.as_view()),
    path(
        "ver-empleado/<pk>/", 
        views.EmpleadoDetailView.as_view(),
        name="empleado_detail"
        ),
    path(
        "add-empleado/",
         views.EmpleadoCreateView.as_view(),
         name= "empleado_add"
         ),
    path("success/",views.SuccessView.as_view(),name="correcto"),
    path("update-empleado/<pk>/", views.EmpleadoUpdateView.as_view(),name="modificar_empleado"),
    path("delete-empleado/<pk>/",views.EmpleadoDeleteView.as_view(),name="eliminar_empleado"),
    path(
        "admin_empleados/", 
        views.ListaAdminempleados.as_view(),
        name="admin_all"
        ),
    
]

empleado/urls.py
#from empleado.empleado.settings.local import STATIC_URL
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # incluimos las URL del App departamento
    re_path("", include("aplications.departamento.urls")),
    re_path("", include("aplications.persona.urls")),
    re_path("", include("aplications.home.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
{% load static %}
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>
        <li><a href="{% url 'persona_app:empleados_all' %}">Listar</a></li>
        <li><a href="{% url 'departamento_app:lista_departamento' %}">Departamentos</a></li>
        <li><a href="{% url 'persona_app:admin_all' %}">Administrar</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar Empleado"></li>
        <li><a href="{% url 'persona_app:empleado_add' %} " class="button">Registrar Nuevo</a></li>
      </ul>
    </div>
  </div>