aplications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

def DesdeApps(self):
         print("hola mundo")

app_name = "departamento_app"         

urlpatterns = [
    
    path("new-departamento/", views.NewDepartamentoView.as_view(), name= "prueba_add"),
    path("lista-departamento/", views.DepartamentoListView.as_view(), name= "lista_departamento"),
]

aplications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "persona_app"

urlpatterns = [
    path(
        "",
        views.InicioView.as_view()
        ,name="inicio"
        ),
    path(
        "listar-todo-empleados/", 
        views.ListAllempleados.as_view(),
        name="empleados_all"
        ),
    path(
        "listar-by-area/<shortname>/",
        views.ListByAreaEmpleado.as_view(),
        name="lista_depa"
        ),
    path("buscar-empleado/", views.ListEmpleadosByKword.as_view()),
    path("listar-habilidades-empleado/", views.Prueba.as_view()),
    path(
        "ver-empleado/<pk>/", 
        views.EmpleadoDetailView.as_view(),
        name="empleado_detail"
        ),
    path(
        "add-empleado/",
         views.EmpleadoCreateView.as_view(),
         name= "empleado_add"
         ),
    path("success/",views.SuccessView.as_view(),name="correcto"),
    path("update-empleado/<pk>/", views.EmpleadoUpdateView.as_view(),name="modificar_empleado"),
    path("delete-empleado/<pk>/",views.EmpleadoDeleteView.as_view(),name="eliminar_empleado"),
    path(
        "admin_empleados/", 
        views.ListaAdminempleados.as_view(),
        name="admin_all"
        ),
    
]

empleado/urls.py
#from empleado.empleado.settings.local import STATIC_URL
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # incluimos las URL del App departamento
    re_path("", include("aplications.departamento.urls")),
    re_path("", include("aplications.persona.urls")),
    re_path("", include("aplications.home.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplications/departamento/models.py
from django.db import models

# Create your models here.





class Departamento(models.Model):
    name = models.CharField("Nombre",max_length=50)
    shor_name = models.CharField("Nombre corto",max_length=20,unique = True)
    anulate = models.BooleanField("Anulado", default=False)
    
    class Meta:
        verbose_name = "Mi Departamento"
        verbose_name_plural = "Mis Departamentos"
        ordering = ["name"]
        unique_together =("name", "shor_name")


    def __str__(self):
        return str(self. id) + " - " + self.name + " - "+ self.shor_name 

aplications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField( max_length=50,)
    apellidos = forms.CharField( max_length=50,)
    departamento = forms.CharField( max_length=50,)
    shor_name = forms.CharField( max_length=50,)

aplications/departamento/views.py
from django.shortcuts import render
from django.views.generic.edit import(FormView) 
from django.urls import reverse_lazy
from django.views.generic import *
from .forms import NewDepartamentoForm
from aplications.persona.models import Empleado
from .models import Departamento



class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/lista.html"
    context_object_name = "departamentos"





class NewDepartamentoView(FormView):

    template_name = "departamento/new-departamento.html"
    form_class = NewDepartamentoForm
    success_url = "/"

    def form_valid(self, form):
        depa = Departamento(
           name=form.cleaned_data["departamento"],
           shor_name =form.cleaned_data["shor_name"]

        )
        depa.save()

        nombre = form.cleaned_data["nombre"]
        apellido = form.cleaned_data["apellidos"]
        Empleado.objects.create(
           first_name=nombre, 
           last_name=apellido,
           job= 1,
           departamento=depa

        )


        return super(NewDepartamentoView,self).form_valid(form)

templates/departamento/lista.html
{% extends 'base.html' %}


{% block title %}

Lista de Departamentos
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
   <div class="grid-x">
      <h1>Lista de Departamentos</h1>
        <div class="cell">
            <table>
                <tbody>
                    {% for departamento in departamentos %} 
                    <tr>
                        <td>{{ departamento.name }}</td>
                        <td>{{ departamento.shor_name }}</td>
                        <td>
                            <a class="button warning" href="{% url 'persona_app:lista_depa' departamento.shor_name %}">Ver Empleados</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
   </div>
</div>



{% endblock content %}

templates/departamento/new-departamento.html
<h1>Crear nuevo departamento</h1>


<form action="" method="POST">{% csrf_token %}

<h3>Datos de Empleado</h3>

<p>Nombre: {{form.nombre}}</p>
<p>Apellidos: {{form.apellidos}}</p>

<h3>Datos de Departamento</h3>

<p>Departamento: {{form.departamento}}</p>
<p>Shor Name: {{form.shor_name}}</p>   


<p> <button type="submit">Agregar departamento</button></p>



</form>